"""added reservation time to restaurant

Revision ID: 1d512b4799d2
Revises: e00d5642a84a
Create Date: 2024-01-18 19:46:56.208111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d512b4799d2'
down_revision: Union[str, None] = 'e00d5642a84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('reservation_hour_length', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'reservation_hour_length')
    # ### end Alembic commands ###
