"""Added restaurant menu tables

Revision ID: 21cd224e5795
Revises: 36d1755c90b8
Create Date: 2024-01-07 18:58:09.516950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cd224e5795'
down_revision: Union[str, None] = '36d1755c90b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_menu_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_menu_categories_id'), 'restaurant_menu_categories', ['id'], unique=False)
    op.create_table('restaurant_menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('inactive', 'unavailable', 'available', name='restaurantmenuitemtype'), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['restaurant_menu_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_menu_items_id'), 'restaurant_menu_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_menu_items_id'), table_name='restaurant_menu_items')
    op.drop_table('restaurant_menu_items')
    op.drop_index(op.f('ix_restaurant_menu_categories_id'), table_name='restaurant_menu_categories')
    op.drop_table('restaurant_menu_categories')
    # ### end Alembic commands ###
