"""adds additional details to reservation

Revision ID: 2abc62d738ae
Revises: cd0013085e1a
Create Date: 2024-01-27 15:32:29.092763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abc62d738ae'
down_revision: Union[str, None] = 'cd0013085e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('additional_details', sa.String(), nullable=False,server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'additional_details')
    # ### end Alembic commands ###
