"""Added order to restaurant menu

Revision ID: 2ebd9bf80801
Revises: 21cd224e5795
Create Date: 2024-01-07 19:34:10.585366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ebd9bf80801'
down_revision: Union[str, None] = '21cd224e5795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_menu_categories', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('restaurant_menu_items', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_menu_items', 'order')
    op.drop_column('restaurant_menu_categories', 'order')
    # ### end Alembic commands ###
