"""Added closed column to restaurant opening hours

Revision ID: 36d1755c90b8
Revises: 32c35c52c9c0
Create Date: 2024-01-06 23:06:05.262588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d1755c90b8'
down_revision: Union[str, None] = '32c35c52c9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_opening_hours', sa.Column('closed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_opening_hours', 'closed')
    # ### end Alembic commands ###
