"""add user to reservation

Revision ID: 58b6e4cd7157
Revises: b0e3b228a6fb
Create Date: 2024-01-19 01:00:26.678970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b6e4cd7157'
down_revision: Union[str, None] = 'b0e3b228a6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reservations', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'user')
    # ### end Alembic commands ###
