"""Added restaurant photo

Revision ID: 6a77798ea1d3
Revises: 2ebd9bf80801
Create Date: 2024-01-13 17:18:02.512028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a77798ea1d3'
down_revision: Union[str, None] = '2ebd9bf80801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'photo_url')
    # ### end Alembic commands ###
