"""Added restaurant settings

Revision ID: a265ed8fba6a
Revises: e619adabbee5
Create Date: 2023-12-04 22:44:39.716973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a265ed8fba6a'
down_revision: Union[str, None] = 'e619adabbee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('email', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('restaurants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('restaurants', 'phone_number')
    op.drop_column('restaurants', 'email')
    # ### end Alembic commands ###
