"""reservation status not nullable

Revision ID: b0e3b228a6fb
Revises: acb6b2b7ac35
Create Date: 2024-01-18 20:32:29.497618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0e3b228a6fb'
down_revision: Union[str, None] = 'acb6b2b7ac35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'status',
               existing_type=postgresql.ENUM('pending', 'rejected', 'accepted', name='reservationstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'status',
               existing_type=postgresql.ENUM('pending', 'rejected', 'accepted', name='reservationstatus'),
               nullable=True)
    # ### end Alembic commands ###
