"""added geo to restaurant

Revision ID: e00d5642a84a
Revises: 94eb8eeb07ae
Create Date: 2024-01-17 21:15:24.934371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00d5642a84a'
down_revision: Union[str, None] = '94eb8eeb07ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'longitude')
    op.drop_column('restaurants', 'latitude')
    # ### end Alembic commands ###
